/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Directorios;

import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

/**
 *
 * @author Carlo Vilchis
 */
public class CreacionP extends javax.swing.JFrame {

    /**
     * Creates new form CreacionP
     */
    public CreacionP() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tipo = new javax.swing.ButtonGroup();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        txtProyecto = new javax.swing.JTextField();
        chkCSS = new javax.swing.JCheckBox();
        chkJS = new javax.swing.JCheckBox();
        chkIMG = new javax.swing.JCheckBox();
        btnCrear = new javax.swing.JButton();
        txtCSS = new javax.swing.JTextField();
        txtJS = new javax.swing.JTextField();
        rdoHTML = new javax.swing.JRadioButton();
        rdoHTML5 = new javax.swing.JRadioButton();
        txtTipo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(680, 460));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 102, 255));
        jLabel1.setText("Nombre :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 10, 135, 32);

        txtProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProyectoActionPerformed(evt);
            }
        });
        getContentPane().add(txtProyecto);
        txtProyecto.setBounds(250, 10, 368, 30);

        chkCSS.setBackground(new java.awt.Color(0, 0, 255));
        chkCSS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkCSS.setText("CSS");
        chkCSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCSSActionPerformed(evt);
            }
        });
        getContentPane().add(chkCSS);
        chkCSS.setBounds(300, 90, 49, 23);

        chkJS.setBackground(new java.awt.Color(0, 51, 255));
        chkJS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkJS.setText("JS");
        chkJS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkJSActionPerformed(evt);
            }
        });
        getContentPane().add(chkJS);
        chkJS.setBounds(300, 130, 50, 23);

        chkIMG.setBackground(new java.awt.Color(0, 153, 255));
        chkIMG.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkIMG.setText("IMG");
        chkIMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkIMGActionPerformed(evt);
            }
        });
        getContentPane().add(chkIMG);
        chkIMG.setBounds(300, 170, 49, 23);

        btnCrear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrear);
        btnCrear.setBounds(370, 310, 194, 40);

        txtCSS.setEnabled(false);
        txtCSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCSSActionPerformed(evt);
            }
        });
        getContentPane().add(txtCSS);
        txtCSS.setBounds(370, 90, 228, 30);

        txtJS.setEnabled(false);
        txtJS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJSActionPerformed(evt);
            }
        });
        getContentPane().add(txtJS);
        txtJS.setBounds(370, 130, 228, 30);

        rdoHTML.setBackground(new java.awt.Color(51, 255, 0));
        Tipo.add(rdoHTML);
        rdoHTML.setFont(new java.awt.Font("Footlight MT Light", 1, 14)); // NOI18N
        rdoHTML.setText("HTML");
        rdoHTML.setFocusCycleRoot(true);
        rdoHTML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoHTMLActionPerformed(evt);
            }
        });
        getContentPane().add(rdoHTML);
        rdoHTML.setBounds(380, 230, 65, 20);

        rdoHTML5.setBackground(new java.awt.Color(102, 153, 0));
        Tipo.add(rdoHTML5);
        rdoHTML5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoHTML5.setText("HTML5");
        rdoHTML5.setToolTipText("");
        rdoHTML5.setFocusCycleRoot(true);
        rdoHTML5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoHTML5ActionPerformed(evt);
            }
        });
        getContentPane().add(rdoHTML5);
        rdoHTML5.setBounds(500, 230, 74, 20);

        txtTipo.setFont(new java.awt.Font("Tunga", 0, 24)); // NOI18N
        txtTipo.setForeground(new java.awt.Color(255, 255, 255));
        txtTipo.setText("Tipos:");
        getContentPane().add(txtTipo);
        txtTipo.setBounds(300, 230, 90, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ABRAHAM\\Pictures\\faraones.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 670, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkIMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkIMGActionPerformed

    }//GEN-LAST:event_chkIMGActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        try {
                 if(rdoHTML.isSelected() || rdoHTML5.isSelected()){ 
                     
            
            File f = new File("C://xampp//htdocs//" + txtProyecto.getText());
            //File RG4L = new File("C://xampp//htdocs//" + txtProyecto.getText());
            if (f.exists()) {
               
                JOptionPane.showMessageDialog(null, "Proyecto que ya existe");
            }else{
                boolean b = f.mkdirs();
                if (b == true) {
                    if (chkCSS.isSelected()) {
                        f = new File("C://xampp//htdocs//" + txtProyecto.getText() + "//css");
                        f.mkdirs();
                        JOptionPane.showMessageDialog(null, "Seleccione un tipo");
                    }
                    if (chkIMG.isSelected()) {
                        f = new File("C://xampp//htdocs//" + txtProyecto.getText() + "//img");
                        f.mkdirs();
                     //   JOptionPane.showMessageDialog(null, "Seleccione un tipo de html");
                    }
                    if (chkJS.isSelected()) {
                        f = new File("C://xampp//htdocs//" + txtProyecto.getText() + "//js");
                        f.mkdirs();
                        JOptionPane.showMessageDialog(null, "Seleccione un tipo");
                    }
                    if (chkCSS.isSelected()) {
                        f = new File("C://xampp//htdocs//" + txtProyecto.getText() + "//css//" + txtCSS.getText() + ".css");
                        f.createNewFile();
                        FileWriter p = new FileWriter("C://xampp//htdocs//" + txtProyecto.getText() + "//css//" + txtCSS.getText() + ".css");
                        PrintWriter c = new PrintWriter(p);
                        c.println("body{ background:lightgreen;} ");
                        c.close();
                        JOptionPane.showMessageDialog(null, "Seleccione un tipo");
                    }

                    if (chkJS.isSelected()) {
                        f = new File("C://xampp//htdocs//" + txtProyecto.getText() + "//js//" + txtJS.getText() + ".js");
                        f.createNewFile();
                        FileWriter p = new FileWriter("C://xampp//htdocs//" + txtProyecto.getText() + "//js//" + txtJS.getText() + ".js");
                        PrintWriter c = new PrintWriter(p);
                        c.println("alert('Conectado correctamente');");
                        c.close();
                       JOptionPane.showMessageDialog(null, "Seleccione un tipo");
                    }

                    if (rdoHTML.isSelected()) {
                        FileWriter p = new FileWriter("C://xampp//htdocs//" + txtProyecto.getText() + "//" + "indexhtml.html");
                        PrintWriter codigo = new PrintWriter(p);
                        codigo.println("<html>");
                        codigo.println("<head>");
                        codigo.println("<title>Pagina->html->normal</title>");
                        codigo.println("</head>");
                        codigo.println("<body>");
                        codigo.println("<marquee> <I><h1>HTML<h1></I></marquee>");
                        codigo.println("</body>");
                        codigo.println("</html>");
                        codigo.close();
                    }
                    if (rdoHTML5.isSelected()) {
                        FileWriter p = new FileWriter("C://xampp//htdocs//" + txtProyecto.getText() + "//" + "indexhtml5.html");
                        PrintWriter codigohtml5 = new PrintWriter(p);
                       codigohtml5.println("<!DOCTYPE html>");
                        codigohtml5.println("<html lang=\"en\">");
                        codigohtml5.println("<meta charset=\"UTF-8\">");
                        codigohtml5.println("<title>Pagina->html5</title>");
                        codigohtml5.println("<script type=" + "'text/javascript'" + "src='js/" + txtJS.getText() + ".js'></script>");
                        codigohtml5.println("<link rel=stylesheet href=" + "'css/" + txtCSS.getText() + ".css'" + ">");
                        codigohtml5.println("<head>");
                        codigohtml5.println("</head>");
                        codigohtml5.println("<body>");
                        codigohtml5.println("<marquee> <I> <h1>HTML5<h1> </I></marquee>");
                        codigohtml5.println("<header>");
                        codigohtml5.println("</header>");
                        codigohtml5.println("<nav>");
                        codigohtml5.println("</nav>");
                        codigohtml5.println("<section>");
                        codigohtml5.println("<article>");
                        codigohtml5.println("</article>");
                        codigohtml5.println("</section>");
                        codigohtml5.println("<aside>");
                        codigohtml5.println("</aside>");
                        codigohtml5.println("<footer>");
                        codigohtml5.println("</footer>");
                        codigohtml5.println("</html>");
                        codigohtml5.println("</body>");
                        codigohtml5.close();
                                                
                        
                        
                    }else{
                     
                     JOptionPane.showMessageDialog(null, "Proyecto creado");
                    }
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Fallo al crear");
                }
            }
                 }else{
                    JOptionPane.showMessageDialog(null, "Necesitas selecionar un HTML, o no estas llenando todos los campos");
                 }
                 
      

        } catch (Exception e) {
            System.out.println(e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearActionPerformed

    private void chkCSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCSSActionPerformed
        if (chkCSS.isSelected()) {
            txtCSS.setEnabled(true);
        } else {
            txtCSS.setEnabled(false);
        }
    }//GEN-LAST:event_chkCSSActionPerformed

    private void txtJSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJSActionPerformed

    }//GEN-LAST:event_txtJSActionPerformed

    private void chkJSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkJSActionPerformed
        if (chkJS.isSelected()) {
            txtJS.setEnabled(true);
        } else {
            txtJS.setEnabled(false);
        }
    }//GEN-LAST:event_chkJSActionPerformed

    private void rdoHTML5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoHTML5ActionPerformed

    }//GEN-LAST:event_rdoHTML5ActionPerformed

    private void rdoHTMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoHTMLActionPerformed

    }//GEN-LAST:event_rdoHTMLActionPerformed

    private void txtProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProyectoActionPerformed

    private void txtCSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCSSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCSSActionPerformed
        
   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreacionP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreacionP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreacionP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreacionP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreacionP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Tipo;
    private javax.swing.JButton btnCrear;
    private javax.swing.JCheckBox chkCSS;
    private javax.swing.JCheckBox chkIMG;
    private javax.swing.JCheckBox chkJS;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rdoHTML;
    private javax.swing.JRadioButton rdoHTML5;
    private javax.swing.JTextField txtCSS;
    private javax.swing.JTextField txtJS;
    private javax.swing.JTextField txtProyecto;
    private javax.swing.JLabel txtTipo;
    // End of variables declaration//GEN-END:variables
}
